#ifndef CONFIG_H
#define CONFIG_H

#define READ_BUFFER_SIZE 256
#define Z_HASH_TABLE_MIN_CAPACITY 16
#define Z_HASH_TABLE_MAX_LOAD_FACTOR 0.7
#define Z_ARRAY_GROWTH_FACTOR 2u
#define Z_DEQUE_GROWTH_FACTOR 2u

#endif
