#ifndef CONFIG_H
#define CONFIG_H

#define Z_CONTAINER_GROUTH_FACTOR 2
#define READ_BUFFER_SIZE 256
#define Z_MIN_CONTAINER_CAPACITY 16

#define Z_HASH_TABLE_MIN_CAPACITY Z_MIN_CONTAINER_CAPACITY
#define Z_HASH_TABLE_MAX_LOAD_FACTOR 0.7
#define Z_ARRAY_GROWTH_FACTOR Z_CONTAINER_GROUTH_FACTOR
#define Z_DEQUE_GROWTH_FACTOR Z_CONTAINER_GROUTH_FACTOR

#endif
